name = "kondo"
license = "MIT"
licenselink = "https://github.com/csdaw/kondo/blob/main/LICENSE.md"
description = "Charlotte's tidy, minimal, blogdown compatible Hugo theme"
homepage = "https://github.com/csdaw/kondo"
tags = ["minimal", "blog", "personal", "simple", "dark mode"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "Charlotte Dawson"
